#!/usr/bin/perl
BEGIN{ $home = `echo \$HOME`; chomp $home}
use lib "$home/PERL_MODULES";

use PBS;

my $pwd  = `pwd`; $pwd =~ s/\n//;
my $pbs = PBS->new;
$pbs->useAllNode(1);
if (defined($ARGV[1])) {
  $pbs->setScriptName("script.pbs.$ARGV[1]");
}
$pbs->setWallTime("24:00:00");	
$pbs->addCmd("cd $pwd");
my $txt = $ARGV[0];
$pbs->addCmd("$txt");
$pbs->submit();
