#!/usr/bin/perl
BEGIN{ $home = `echo \$HOME`; chomp $home}
use lib "$home/PERL_MODULES";

use PBS;
my $pwd  = `pwd`; $pwd =~ s/\n//;
my $pbs = PBS->new;
$pbs->setPlatform("panda");
$pbs->setWallTime("24:00:00");
$pbs->setMemory("8G");	
$pbs->setEmail("ole2001\@med.cornell.edu");
$pbs->addCmd("cd $pwd");
if (defined($ARGV[1])) {
  $pbs->setScriptName("script.pbs.$ARGV[1]");
}
my $txt = $ARGV[0];
$pbs->addCmd("$txt");
$pbs->submit();
