#!/bin/bash
file=$1
dir=`pwd | sed 's/\/Users\/olivier\///'`
if [[ $2 != "" ]]
then ssh ole2001@descartes.med.cornell.edu "mkdir -p ~/$dir"
fi
echo "scp $1 ole2001@descartes.med.cornell.edu:$dir/$1"
scp $1 ole2001@descartes.med.cornell.edu:$dir/$1
