#!/bin/bash
file=$1
dir=`pwd | sed 's/\/Users\/olivier\///'`
if [[ $2 != "" ]]
then ssh ole2001@direwulf.med.cornell.edu "mkdir -p ~/$dir"
fi
echo "scp $1 ole2001@direwulf.med.cornell.edu:$dir/"
scp $1 ole2001@direwulf.med.cornell.edu:$dir/
