double bino(int x, int N, double p); 
double lcumhyper(int i, int s1, int s2, int N); 
double cumhyper(int i, int s1, int s2, int N); 
double cumbino(int k, int N, double p); 
double bico(int n, int k);
double lbico(int n, int k);
double factln(int n);
double gammln(double xx);
double factrl(int n) ;
void nrerror(char str[]);
double hypergeom(int i, int s1, int s2, int N);
